### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [digikar99/trivial-coerce#1]
Building with SBCL 2.1.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id fb365b62affeb5e84aebd8a7a338e39a1684fa09

*trivial-coerce* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BE8103}>: Component "polymorphic-functions" not found, required by #<SYSTEM "trivial-coerce">

```

*trivial-coerce/tests* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BE8103}>: Component "polymorphic-functions" not found, required by #<SYSTEM "trivial-coerce">

```

[Full log here](http://report.quicklisp.org/2021-07-18/failure-report/trivial-coerce.html)

**Comment by digikar99** [comment]
Erm, complicated story I guess.

It was originally requested that [trivial-coerce be fetched from the releases](https://github.com/quicklisp/quicklisp-projects/issues/1984). However, the release v0.0.1 depended on my version of trivial-types, as the [original author of trivial-types had archived m2ym/trivial-types](https://github.com/quicklisp/quicklisp-projects/issues/1983); the original version is still incomplete in accordance with CLHS terminologies, and a bit misleading in a few cases. And IIUC, [quicklisp is still relying on m2ym/trivial-types](https://github.com/quicklisp/quicklisp-projects/blob/master/projects/trivial-types/source.txt).

Quicklisp had failed to build using my version of trivial-types back then; the breakage was perhaps primarily due to cl-syntax. But, [a fix was committed to lisp-maintainers/cl-syntax and it was requested that this be added in place of the now archived m2ym/cl-syntax](https://github.com/quicklisp/quicklisp-projects/issues/2011).

**Comment by digikar99** [comment]
Possible solutions I see include:

1. I rename digikar99/trivial-types to trivial-types2 and create/update the trivial-coerce release.

But I don't want to do this; I'd rather prefer some methodology/protocol to transfer/update any archived repositories. Me renaming this to trivial-types2 feels indicative of the community getting a trivial-types3 10 years down the line, which feels ugly.

2. quicklisp update's trivial-types to the updated version; and I revert the probably cl-syntax breaking commits to trivial-types to and leave those fixes/changes as wont-fix. 

No changes to cl-syntax would be *inherently* required; but cl-syntax would still be without a maintainer, and there is a [pending bug/fix independent of trivial-types](https://stackoverflow.com/questions/66567953/readtable-conflicts-with-cl-annot-cl-syntax-jonathan-and-pythonic-string-read); so cl-syntax will need to be updated independent of the issues related to trivial-coerce and trivial-types.

3. quicklisp update's both of trivial-types and cl-syntax to the new URLs, and update trivial-coerce so that it gets fetched from the releases.

I just tested in portacle, using the latest quicklisp release, with the following changes: (i) my version of trivial-types / latest-commit (ii) trivial-coerce tagged v0.0.1 (iii) lisp-maintainers version of cl-syntax / latest commit. The first two allow trivial-coerce to compile/load, but breaks systems that depend on cl-syntax. Doing the third allows systems that depend on cl-syntax to compile/load. I specifically tested jonathan and clack-middleware-clsql. It's possible there could be breakages other than this; but I'm not sure how to locate them.

I'd be glad to know if there are other solutions.

My personal preference is 3; but if there are other breakages which are not simple to fix, 2 seems better, to avoid involving more repositories into this mess.

**Comment by digikar99** [comment]
Closing this because new quicklisp version has arrived.
