### ISSUE TITLE
If it depnds on ctype, it shouldn't be called TRIVIAL-coerce

### ISSUE THREAD

**Issue by Yehouda** [digikar99/trivial-coerce#3]
ctype is far from being a trivial thing, so anything that depends should be called trivial.

**Comment by digikar99** [comment]
I agree, and even besides ctypes, there are other non-trivial dependencies as well.

When I had started out, the [only dependencies were introspect-environment and trivial-types](https://github.com/digikar99/trivial-coerce/blob/a8d38e8b7edfe767ecef47f5929a34ac2d838bb2/trivial-coerce.asd); however, any better compile time type parsing has led to non-trivial dependencies.

Since now it heavily depends on extensible-compound-types and cl-form-types, I might rename it to extensible-compound-types-coerce, or shift the project to that repository. 

Thanks for the feedback!

**Comment by digikar99** [comment]
Renamed to extensible-optimizing-coerce.
